### ISSUE TITLE
CO2: Make it consistent per group

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltAddCO2#10]
Dear @maurolepore , 

when reviewing the Bundesbank Output, we realized that the `co2e_lower` and `co2e_upper` are not consistent per group. What I mean with that is that the same group, e.g. `tilt_subsector` == "chemistry has for `benchmark` == "tilt_subsector" multiple different values for `co2e_lower` and `co2e_upper`. This should not be the case acc. to the grouping documented [here](https://github.com/2DegreesInvesting/tiltIndicatorAfter/pull/214/files/4fc160be5f0c34ad9741f3a9dd0bae08532a3d49#diff-ea83e0f67e6019a3e4f1a08040aa19932717c6d402df22e97149ec33dd6a6542). 

Can you please investigate where this issue comes from and see if / how to solve it? See below the code I used to identify some of the cases (not a reprex, but I hope it still makes your life easier ;) )

```{r}
# load data
em_prod <- read_csv(here("Bundesbank_data_2024-06-27/emissions_profile_at_product_level.csv"))

#(1)There are multiple co2_lower & co2_upper for benchmark == all
all_co2lower_upper <- em_prod |> 
  filter(benchmark == "all") |> 
  select(benchmark, co2e_lower, co2e_upper) |> 
  distinct()
 
#(2) There are multiple co2_lower & co2_upper for benchmark == "tilt_subsector" & tilt_subsector == "chemicals"
tilt_sec_co2lower_upper <- em_prod |> 
  filter(benchmark == "tilt_subsector") |> 
  filter(tilt_subsector == "chemicals") |>
  select(benchmark, tilt_subsector, co2e_lower, co2e_upper) |> 
  distinct()
  

```

Thanks! 
Tilman 

cc' @AnneSchoenauer

**Comment by maurolepore** [comment]
Thanks @Tilmon 

tiltIndicator doesn't deal with those columns. I'll transfer this issue to tiltAddCO2.

**Comment by Tilmon** [comment]
@maurolepore when tackling this issue, please be aware that the ultimate goal is not anymore to show the columns `co2e_lower` and `co2e_upper` in the normal output tables, but to summarize them in a separate table, as requested in this ticket 2DegreesInvesting/tiltPolish#3 . Flagging this here in case it affects the way you aim to solve it.

**Comment by maurolepore** [comment]
* I'll start with the other issue 2DegreesInvesting/tiltPolish#3 

That ask is clearer and therefore easier for me to add some value in a more predictable timeframe. Then I can continue trying to understand and fix the bug here while you review this output.

**Comment by maurolepore** [comment]
@Tilmon can you please check this reprex. You code might be missleading. Based on the groupings we defined, we expect unique values not only by `c("benchmark")` but by both `c("benchmark", "emission_profile")`.

See [this](https://github.com/2DegreesInvesting/tiltAddCO2/blob/main/tests/testthat/_snaps/group_benchmarks.md)

```
# $all
# [1] "benchmark"        "emission_profile"
```

<details>

``` r
# SETUP

library(tiltIndicatorAfter)
library(tiltToyData)
library(readr, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)

options(readr.show_col_types = FALSE)

companies <- read_csv(toy_emissions_profile_any_companies())
products <- read_csv(toy_emissions_profile_products_ecoinvent())
europages_companies <- read_csv(toy_europages_companies())
ecoinvent_activities <- read_csv(toy_ecoinvent_activities())
ecoinvent_europages <- read_csv(toy_ecoinvent_europages())
isic_name <- read_csv(toy_isic_name())

result <- profile_emissions(
  companies,
  products,
  europages_companies = europages_companies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_europages = ecoinvent_europages,
  isic = isic_name
)

product <- result |> unnest_product()



# INTERESTING

# Expected groupings: For all we expect unique values by not only `benchmark`
# but also `emission_profile`
# https://github.com/2DegreesInvesting/tiltAddCO2/blob/main/tests/testthat/_snaps/group_benchmarks.md
# $all
# [1] "benchmark"        "emission_profile"

expected_grouping <- c("benchmark", "emission_profile")
product |> 
  filter(benchmark == "all") |> 
  select(all_of(expected_grouping), co2e_lower, co2e_upper) |> 
  distinct()
#> # A tibble: 3 × 4
#>   benchmark emission_profile co2e_lower co2e_upper
#>   <chr>     <chr>                 <dbl>      <dbl>
#> 1 all       high                212.       601.   
#> 2 all       low                   0.476      0.825
#> 3 all       medium               -9.36      12.2

em_prod <- product
# Your code seems to produce the wrong result but it's missing `emission_profile`
em_prod |> 
  filter(benchmark == "all") |> 
  select(benchmark, co2e_lower, co2e_upper) |> 
  distinct()
#> # A tibble: 3 × 3
#>   benchmark co2e_lower co2e_upper
#>   <chr>          <dbl>      <dbl>
#> 1 all          212.       601.   
#> 2 all            0.476      0.825
#> 3 all           -9.36      12.2
```

</details>

**Comment by Tilmon** [comment]
Hi @maurolepore , 

I checked your reprex but it still shows multiple values for each `benchmark` == "all" x `emission_profile` combination. 

Reprex I used: 

```{r}
expected_grouping <- c("benchmark", "emission_profile")
em_prod |> 
  filter(benchmark == "all") |> 
  select(all_of(expected_grouping), co2e_lower, co2e_upper) |> 
  distinct()
```

... where em_prod is the emission_profile product-level output file you uploaded [here](https://github.com/2DegreesInvesting/tiltOutput/releases/tag/v0.0.0.9003).

**Comment by Tilmon** [comment]
But @maurolepore I thought we also closed this as not planned? But now I see I apparently re-opened it... I suggest we put it on hold for now and only pick it up if we get problems after you completed this task 2DegreesInvesting/tiltOutput/issues/6. OK?

**Comment by maurolepore** [comment]
> But now I see I apparently re-opened it...

Yeah I also thought we closed it but then I got confused. 

OK, super happy to close it for now.
